// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-tYUcQNQ5L8OvrVpXOKNh-d1X4MiKdVs',
    appId: '1:277644667344:web:0e0cd72dffea10ee8831d5',
    messagingSenderId: '277644667344',
    projectId: 'nutriscan-a66ae',
    authDomain: 'nutriscan-a66ae.firebaseapp.com',
    storageBucket: 'nutriscan-a66ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBPn-i9SmXwQRbVUCuVh5JfTf3KpFYTf8',
    appId: '1:277644667344:android:3faf0131b93b620f8831d5',
    messagingSenderId: '277644667344',
    projectId: 'nutriscan-a66ae',
    storageBucket: 'nutriscan-a66ae.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWkQqPqY14x6psMdM7aV3GTJ4SwZVHT58',
    appId: '1:277644667344:ios:94858f6c0a1078868831d5',
    messagingSenderId: '277644667344',
    projectId: 'nutriscan-a66ae',
    storageBucket: 'nutriscan-a66ae.firebasestorage.app',
    iosBundleId: 'com.example.nutriscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWkQqPqY14x6psMdM7aV3GTJ4SwZVHT58',
    appId: '1:277644667344:ios:94858f6c0a1078868831d5',
    messagingSenderId: '277644667344',
    projectId: 'nutriscan-a66ae',
    storageBucket: 'nutriscan-a66ae.firebasestorage.app',
    iosBundleId: 'com.example.nutriscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-tYUcQNQ5L8OvrVpXOKNh-d1X4MiKdVs',
    appId: '1:277644667344:web:11ddf4402097a2fc8831d5',
    messagingSenderId: '277644667344',
    projectId: 'nutriscan-a66ae',
    authDomain: 'nutriscan-a66ae.firebaseapp.com',
    storageBucket: 'nutriscan-a66ae.firebasestorage.app',
  );
}
