import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'app/nutriscan_app.dart';
import 'firebase_options.dart';

/// Point Firebase Auth and Firestore at local emulators instead of production.
///
/// Debug builds only: release builds always talk to the real project, so
/// nothing here can affect production data.
const bool _useEmulators = kDebugMode;

/// Where the emulators are reachable from the running app.
///
/// Loopback on purpose. FlutterFire rewrites this per platform: on an Android
/// emulator it becomes 10.0.2.2, the alias for the host's own loopback, and
/// that is what the device actually dials - it logs the swap as `Mapping Auth
/// Emulator host "127.0.0.1" to "10.0.2.2"`. The tunnels below are belt and
/// braces for tooling that does no such rewriting; the app does not need them:
///
///   adb reverse tcp:8080 tcp:8080
///   adb reverse tcp:9099 tcp:9099
///
/// One trap is worth knowing about, because it looks like a broken emulator
/// and is not. The Auth emulator holds its accounts in memory and loses them
/// when it restarts, while the app keeps its session on disk and restores it
/// without asking the server. A device can therefore be holding a session for
/// an account that no longer exists: reads go on working, because the
/// Firestore emulator does not check that the id belongs to anybody, and the
/// first call that genuinely needs the auth server - creating an account, for
/// instance - fails with "no user record" and signs the device out. Clear the
/// app's stored session whenever the emulators are restarted:
///
///   adb shell pm clear com.azim.nutriscan
const String _emulatorHost = '127.0.0.1';
const int _firestoreEmulatorPort = 8080;
const int _authEmulatorPort = 9099;

/// Entry point. All UI setup lives in [NutriScanApp] so this file stays tiny.
Future<void> main() async {
  // Required before any plugin is used ahead of runApp().
  WidgetsFlutterBinding.ensureInitialized();

  await _initializeFirebase();

  runApp(const NutriScanApp());
}

/// Connects the app to the Firebase project.
///
/// A failed connection is logged and the app still starts: the profile screen
/// and the scan flow's camera still work, and anything needing Firebase
/// reports its own error when used.
Future<void> _initializeFirebase() async {
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    if (_useEmulators) {
      await _connectEmulators();
    }

    await _activateAppCheck();
  } catch (error) {
    debugPrint('Firebase initialisation failed: $error');
  }
}

Future<void> _connectEmulators() async {
  FirebaseFirestore.instance.useFirestoreEmulator(
    _emulatorHost,
    _firestoreEmulatorPort,
  );
  await FirebaseAuth.instance.useAuthEmulator(_emulatorHost, _authEmulatorPort);
}

/// Attests that requests come from a genuine build of this app.
///
/// Debug builds use the debug provider, which needs its token registered once
/// in the Firebase console; release builds use Play Integrity. The token is
/// printed by the Firebase SDK itself - treat it as a credential, keep it out
/// of source control, and never paste it anywhere public.
///
/// The backend does not enforce App Check yet, so a failure here is logged
/// without a token value and the app carries on.
Future<void> _activateAppCheck() async {
  try {
    await FirebaseAppCheck.instance.activate(
      providerAndroid: kDebugMode
          // The debug token is generated by the SDK, never hard-coded here.
          ? const AndroidDebugProvider()
          : const AndroidPlayIntegrityProvider(),
    );
  } catch (error) {
    debugPrint('App Check activation failed: ${error.runtimeType}');
  }
}
